import React from 'react'

export const entireClick = {
  A1: true,
  A2: true,
  A3: true,
  A4: true,
  A5: true,
  A6: true,
  A7: true,
  A8: true,
  B1: true,
  B2: true,
  C1: true,
  C2: true,
  C3: true,
  C4: true,
  D1: true,
  D2: true,
  D3: true,
  D4: true,
  D5: true,
  D6: true,
  D7: true,
  D8: true,
  D9: true,
  D10: true,
  D11: true,
  D12: true,
  D13: true,
  D14: true,
  E1: true,
  E2: true,
  E3: true,
  E4: true,
  E5: true,
  E6: true,
  E7: true,
  E8: true,
  E9: true,
  E10: true,
  E11: true,
  E12: true,
  E13: true,
  E14: true,
  E15: true,
  E16: true,
  F1: true,
  F2: true,
  F3: true,
  F4: true,
  F5: true,
  F6: true,
  F7: true,
  F8: true,
  G1: true,
  G2: true,
  G3: true,
  G4: true,
  G5: true,
  G6: true,
  H1: true,
  H2: true,
  H3: true,
  H4: true,
  I1: true,
  I2: true,
}
export const entireRemove = {}
export const halfClick = {
  A1: true,
  A2: false,
  A3: true,
  A4: false,
  A5: true,
  A6: false,
  A7: true,
  A8: false,
  B1: true,
  B2: false,
  C1: true,
  C2: false,
  C3: true,
  C4: false,
  D1: true,
  D2: false,
  D3: true,
  D4: true,
  D5: true,
  D6: false,
  D7: true,
  D8: false,
  D9: true,
  D10: false,
  D11: true,
  D12: false,
  D13: true,
  D14: false,
  E1: true,
  E2: false,
  E3: true,
  E4: false,
  E5: true,
  E6: false,
  E7: true,
  E8: false,
  E9: false,
  E10: true,
  E11: false,
  E12: true,
  E13: false,
  E14: true,
  E15: false,
  E16: true,
  F1: false,
  F2: true,
  F3: true,
  F4: true,
  F5: false,
  F6: false,
  F7: true,
  F8: false,
  G1: true,
  G2: false,
  G3: true,
  G4: true,
  G5: false,
  G6: false,
  H1: true,
  H2: false,
  H3: false,
  H4: true,
  I1: false,
  I2: true,
}

export const create_refs = [
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
  React.createRef(),
]
